### ISSUE TITLE
login button does nothing

### ISSUE THREAD

**Issue by hemna** [operacle/checkcle#44]
Installed via docker compose, hit the site, used the default user and password, clicked login.

login button clicks...and does nothing.

**Comment by hemna** [comment]
![Image](https://github.com/user-attachments/assets/1cde209a-f928-4a99-baa4-c30f546d9d82)

**Comment by hemna** [comment]
No login/auth error message in the ui telling me that the auth failed, but auth failures in the js console.

**Comment by SamKr** [comment]
Same issue here, fresh install. 

And, same issue on the live demo: 

https://demo.checkcle.io/login

**Comment by smokey007** [comment]
Same here

**Comment by tolaleng** [comment]
> ![Image](https://github.com/user-attachments/assets/1cde209a-f928-4a99-baa4-c30f546d9d82)

@hemna Kindly help clean up and pull the latest image I just updated.

**Comment by hemna** [comment]
The login page shows invalid credentials at least now....but still can't login using the documented credentials of
admin@exmaple.com
Admin123456

<img width="581" alt="Image" src="https://github.com/user-attachments/assets/3dfc5874-cde7-475f-87ee-e821118a43e7" />

**Comment by SamKr** [comment]
I created a completely new vm, so fully clean, but still getting this: 

![Image](https://github.com/user-attachments/assets/95a0037e-5d56-4155-b1b9-b098e8c75fcc)

**Comment by smokey007** [comment]
I deleted all the files from the directory and repulled the image but still get it. what env variable did you use for dark mode?

**Comment by smokey007** [comment]
version: '3.9'

services:
  checkcle:
    image: operacle/checkcle:latest
    container_name: checkcle
    restart: unless-stopped
    ports:
      - "8293:8090"  # Web Application
    volumes:
      - /opt/checkcle/pb_data:/mnt/pb_data  # Host directory mapped to container path
    ulimits:
      nofile:
        soft: 4096
        hard: 8192

**Comment by SamKr** [comment]
> Could you please share your Docker Compose configuration? Did you customize the volume paths? I've double-checked it on my side, and everything is working fine with the login. 

I used the docker compose file as-is, no customisations.

```yaml
services:
  checkcle:
    image: operacle/checkcle:latest
    container_name: checkcle
    restart: unless-stopped
    ports:
      - "8090:8090"  # Web Application
    volumes:
      - /opt/pb_data:/mnt/pb_data  # Host directory mapped to container path
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
```

> One more thing, could you please remove the existing Docker image to ensure a clean setup?

It's a new VM, so there was nothing left of the old docker image. The OS is Debian 12.
